<a href="https://colab.research.google.com/github/aviralshukla2007-hue/project_calc/blob/main/Arrays_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# To create 1D array using NumPy

import numpy as np
a = [1,2,3,4]
arr = np.array(a)
print("List in Python:",a)
print("Array in NumPy:",arr)

List in Python: [1, 2, 3, 4]
Array in NumPy: [1 2 3 4]

In [ ]:
# To check the datatype of the 1D array
print(type(a))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>

In [ ]:
#To create a multi-dimension array using NumPy

import numpy as np

list_1 = [1,2,3,4]
list_2 = [5,6,7,8]
list_3 = [7,8,9,10]

arr = np.array([list_1,
                list_2,
                list_3])

print("Numpy multi-dimensional array in python\n:",arr)

Numpy multi-dimensional array in python
: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 7  8  9 10]]

In [ ]:
import numpy as np

sample_array = np.array([1,2,3,4,5,6,7,8,9,10])
sample_array_1 = np.array([1.6, 2.6, 3.6, 4.6, 5.6])

print("Data type of the first array:",sample_array.dtype)
print("Data type of the second array:",sample_array_1.dtype)

Data type of the first array: int64
Data type of the second array: float64

In [ ]:
# Creation of Array using numpy.array()

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Array:",arr)

Array: [ 1  2  3  4  5  6  7  8  9 10]

In [ ]:
import numpy as np
sample_array = np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])

print("shape of the array :",
      sample_array.shape)

shape of the array : (5, 3)

In [ ]:
import numpy as np
var = "Hello There!"
arr=np.fromiter(var, dtype = 'U2')
print("fromiter() arr:", arr)

fromiter() arr: ['H' 'e' 'l' 'l' 'o' ' ' 'T' 'h' 'e' 'r' 'e' '!']

In [ ]:
import numpy as np
x = [1,2,3,4]
y = [5,6,7,8]
z = [9,10,11,12]

arr = np.array([x,
                y,
                z])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [ ]:
import pandas as pd
import numpy as np
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
import pandas as pd
import numpy as np
dates = pd.date_range("20260617", periods=6)
dates

DatetimeIndex(['2026-06-17', '2026-06-18', '2026-06-19', '2026-06-20',
               '2026-06-21', '2026-06-22'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
import pandas as pd
In [9]: df2 = pd.DataFrame(
    {
    "A": 1.0,
    "B": pd.Timestamp("20260617"),
    "C": pd.Series(1, index=list(range(4)), dtype="float32"),
    "D":np.array([3]*4, dtype="int32"),
    "E":pd.Categorical(["test","train","test","train"]),
    "F":"foo",
    }
)

In [10]: df2

     A          B    C  D      E    F
0  1.0 2026-06-17  1.0  3   test  foo
1  1.0 2026-06-17  1.0  3  train  foo
2  1.0 2026-06-17  1.0  3   test  foo
3  1.0 2026-06-17  1.0  3  train  foo

In [ ]:
import pandas as pd
In [2]: df = pd.DataFrame(
    {
        "Name":[
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

In [3]: df
In [4]: df["Age"]
In [5]: ages = pd.Series([22, 35, 58], name="Age")
In [6]: ages
In [7]: df["Age"].max()

58

In [ ]:
In [8]: ages.max()

58

In [ ]:
In [9]: df.describe()

In [ ]:
import numpy as np

my_list = [1,2,3,4]

In [ ]:
import numpy as np

my_list = [1,2,3,4,5,6]

my_list = my_list * 2

print(my_list)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [ ]:
import numpy as np

array = np.array([1,2,3,4])*2

print(array)

print(type(array))

[2 4 6 8]
<class 'numpy.ndarray'>

In [ ]:
#Working with multi dimensional NumPy Arrays
import numpy as np

array = np.array([['A','B','C'],
                  ['D','E','F'],
                  ['G','H','I']])

print(array.ndim)
print(array.shape)
print(array[0,2])

2
(3, 3)
I

In [ ]:
#Methods of Array Slicing using NumPy
import numpy as np

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

#array[start:end:step]

print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

In [ ]:
import numpy as np

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','']]])
print(array[:, ::-2])

word = print(array[0,0,0]+array[2,0,0]+array[2,0,0])

print(array.ndim)

[[['G' 'H' 'I']
  ['A' 'B' 'C']]

 [['P' 'Q' 'R']
  ['J' 'K' 'L']]

 [['Y' 'Z' '']
  ['S' 'T' 'U']]]
ASS
3

In [1]:
import numpy as np

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)

[5 7 9]